spring:
  application:
    name: demo-provider # Spring 应用名

  profiles:
    active: dev
  cloud:
    nacos:
      # Nacos 作为注册中心的配置项，对应 NacosDiscoveryProperties 配置类
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos 服务器地址
        service: ${spring.application.name} # 注册到 Nacos 的服务名。默认值为 ${spring.application.name}。

server:
  port: 18001 # 服务器端口。默认为 8080
management:
  endpoints:
    web:
      exposure:
        include: '*' # 需要开放的端点。默认值只打开 health 和 info 两个端点。通过设置 * ，可以开放所有端点。
  endpoint:
    # Health 端点配置项，对应 HealthProperties 配置类
    health:
      enabled: true # 是否开启。默认为 true 开启。
      show-details: ALWAYS # 何时显示完整的健康信息。默认为 NEVER 都不展示。可选 WHEN_AUTHORIZED 当经过授权的用户；可选 ALWAYS 总是展示。


mybatis-plus:
  # 指定Mapper.xml文件位置,可以是数组
  mapperLocations: classpath*:/mapper/**/*.xml
  configuration:
    # sql输出设置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 别名包扫描路径，通过该属性可以给包中的类注册别名，注册后在 Mapper 对应的 XML 文件中可以直接使用类名，而不用带包名
  typeAliasesPackage: com.example.*.entity
  global-config:
    db-config:
      # 配置逻辑删除相关
      # 全局逻辑删除的实体字段名(根据实际情况配置)
      logic-delete-field: del
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1

knife4j:
  # 开启增强功能
  enable: true